"""
Importa o roster do corpo militar para o PostgreSQL.
Uso: python -m backend.scripts.seed_militar
"""

import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from dotenv import load_dotenv
load_dotenv()

import psycopg

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    print("DATABASE_URL não configurado no .env"); sys.exit(1)

_ORDEM = {
    "Fundador": -2, "Supremo": -1,
    "Comandante-Geral": 0, "Comandante": 1, "Subcomandante": 2, "Marechal": 3,
    "General": 4, "Coronel": 5, "Tenente-Coronel": 6, "Major": 7,
    "Capitão": 8, "Tenente": 9, "Aspirante a Oficial": 10, "Subtenente": 11,
    "Sargento": 12, "Cabo": 13, "Soldado": 14,
}

ROSTER = [
    # ── Alto Comando Supremo
    ("Jodie-Foster",     "Fundador"),
    ("rafacv",           "Supremo"),
    ("Horcrux-",         "Supremo"),
    ("Leticinha-_-",     "Supremo"),
    # ── Capitão
    ("kaique0834",       "Capitão"),
    ("kikit4",           "Capitão"),
    ("_BelleBoyer",      "Capitão"),
    ("anajulia9628",     "Capitão"),
    # ── Tenente
    ("By.",              "Tenente"),
    ("SunWickAs",        "Tenente"),
    ("davi1",            "Tenente"),
    ("GabrielSantoss",   "Tenente"),
    ("blezzed",          "Tenente"),
    ("?:.tami.:?",       "Tenente"),
    ("J0N45_",           "Tenente"),
    # ── Aspirante a Oficial
    ("mineeeeds",        "Aspirante a Oficial"),
    ("Deamo",            "Aspirante a Oficial"),
    (".Santoss",         "Aspirante a Oficial"),
    ("vitorhugo962",     "Aspirante a Oficial"),
    ("saesarxvcnfyv",    "Aspirante a Oficial"),
    ("BADBOY1999",       "Aspirante a Oficial"),
    ("Omeruo.",          "Aspirante a Oficial"),
    ("Wyra",             "Aspirante a Oficial"),
    ("oPeralta",         "Aspirante a Oficial"),
    ("Bruninho.",        "Aspirante a Oficial"),
    ("DaFuria777",       "Aspirante a Oficial"),
    ("eudesbingoo",      "Aspirante a Oficial"),
    ("mellzinhaK",       "Aspirante a Oficial"),
    ("emineste",         "Aspirante a Oficial"),
    ("rockmillew41",     "Aspirante a Oficial"),
    ("Carolina2_8",      "Aspirante a Oficial"),
    ("Mortifique",       "Aspirante a Oficial"),
    ("totininho",        "Aspirante a Oficial"),
    ("MC.ZULUZAO",       "Aspirante a Oficial"),
    ("filipetreze",      "Aspirante a Oficial"),
    ("bielgoat",         "Aspirante a Oficial"),
    ("Hadley.",          "Aspirante a Oficial"),
    ("pedrin18",         "Aspirante a Oficial"),
    # ── Subtenente
    (".::JoaoG::.",      "Subtenente"),
    ("ArthurZ3Party",    "Subtenente"),
    ("Peruzzi",          "Subtenente"),
    ("raquellkelly",     "Subtenente"),
    ("edszika20",        "Subtenente"),
    ("elison789",        "Subtenente"),
    ("PadrinPDN",        "Subtenente"),
    ("ablubebe",         "Subtenente"),
    ("Zebonitinho58",    "Subtenente"),
    ("Odanna",           "Subtenente"),
    ("9lucasloco9",      "Subtenente"),
    ("Hwberto",          "Subtenente"),
    ("nalashitz",        "Subtenente"),
    ("Jarlys",           "Subtenente"),
    ("Th1ago",           "Subtenente"),
    ("Salem-Vexmoor",    "Subtenente"),
    ("bearGrizzlybear",  "Subtenente"),
    ("Obscuron",         "Subtenente"),
    # ── Sargento
    ("cserafim16",       "Sargento"),
    ("CaioBR4",          "Sargento"),
    ("JonyJonys",        "Sargento"),
    ("Pedriinho_013",    "Sargento"),
    ("-DM!",             "Sargento"),
    ("vieirinhaBruxo",   "Sargento"),
    ("julianaosabe",     "Sargento"),
    ("tiago68303",       "Sargento"),
    ("legalblcf",        "Sargento"),
    ("PRAvenaa",         "Sargento"),
    ("DeimonFhaagg",     "Sargento"),
    ("kakashi127",       "Sargento"),
    # ── Cabo
    ("Flokiih",          "Cabo"),
    ("FULano.Ab13",      "Cabo"),
    (".-Podh-.",         "Cabo"),
    ("nogueeira_jv",     "Cabo"),
    ("Davikjkj",         "Cabo"),
    ("xX_Monster_Xx",    "Cabo"),
    ("brenolopesPop",    "Cabo"),
    ("DEP-JackDaniels",  "Cabo"),
    ("Fruto",            "Cabo"),
    ("MiaKitty",         "Cabo"),
    ("tavzz",            "Cabo"),
    ("daniboy30",        "Cabo"),
    ("FrostkingReal",    "Cabo"),
    ("Camillaa27",       "Cabo"),
    ("Giinxzz",          "Cabo"),
    ("ser03y04",         "Cabo"),
    ("iDeeh-",           "Cabo"),
    ("gabrielvag25",     "Cabo"),
    ("Lulums13",         "Cabo"),
    ("changed",          "Cabo"),
    ("PedroMelo=",       "Cabo"),
    (".frentzen.",       "Cabo"),
    ("ser-5i-652",       "Cabo"),
    ("dvd.",             "Cabo"),
    ("XandeGatoBB",      "Cabo"),
    ("Moises_0977",      "Cabo"),
    ("Hypnosz",          "Cabo"),
    # ── Soldado
    ("=-Mclucas123-=",   "Soldado"),
    ("-x-",              "Soldado"),
    ("FULano.Ab123",     "Soldado"),
    ("lucas3717",        "Soldado"),
    ("@mchenrique!",     "Soldado"),
    ("Danzyon",          "Soldado"),
    ("starnicola39",     "Soldado"),
    ("Dep-Baconpapela",  "Soldado"),
    ("plynd",            "Soldado"),
    ("VictorAtaides",    "Soldado"),
    ("Nenhum",           "Soldado"),
    ("last11",           "Soldado"),
    ("REATIAMANDA",      "Soldado"),
    ("robsclei67",       "Soldado"),
    ("Fr1s",             "Soldado"),
    ("Ivanovich10",      "Soldado"),
    ("djgiselle@paula",  "Soldado"),
    ("Moqorro",          "Soldado"),
    ("Strawberry:",      "Soldado"),
    ("-Hiagoban",        "Soldado"),
    ("guilher43664",     "Soldado"),
    ("amiguinhovc",      "Soldado"),
    ("bbbjulialoka",     "Soldado"),
    ("Serl426-9-7",      "Soldado"),
    ("CauanDoLol",       "Soldado"),
    ("Twisterrrrrrrrr",  "Soldado"),
    ("FujiroKamyamot0",  "Soldado"),
    ("ser-9w-62-5",      "Soldado"),
    ("MNVZP",            "Soldado"),
    ("Karlet",           "Soldado"),
    ("danttee",          "Soldado"),
    ("milena83043",      "Soldado"),
    ("mcryansp123",      "Soldado"),
    ("mariap.15",        "Soldado"),
    ("dudaaaf",          "Soldado"),
    ("SaudadsDoHabbo",   "Soldado"),
    ("Beahzin",          "Soldado"),
    ("Paola1343",        "Soldado"),
    ("Nenhum.",          "Soldado"),
    ("AmorinhaaGata",    "Soldado"),
    ("governista",       "Soldado"),
    ("ogataodasruas.c",  "Soldado"),
    ("AposentadoTenor",  "Soldado"),
    ("quentona",         "Soldado"),
    ("Infestissaum",     "Soldado"),
    ("Surtadaq12",       "Soldado"),
    ("ian5116",          "Soldado"),
    ("Calvin.Fran.Abg",  "Soldado"),
    ("gabyy.",           "Soldado"),
    ("Playerzinrico10",  "Soldado"),
    ("Kawaiso",          "Soldado"),
    ("bxerickxd82",      "Soldado"),
    ("Halls.de.Gabby",   "Soldado"),
    ("Lostlilweep",      "Soldado"),
    ("FULano.Ab14",      "Soldado"),
    ("NaimI",            "Soldado"),
    ("hendryu",          "Soldado"),
    ("manuel@@",         "Soldado"),
    ("trying.ART",       "Soldado"),
    ("Sahara:",          "Soldado"),
    ("Cayaha",           "Soldado"),
    ("Vtrkimberly",      "Soldado"),
    ("ser3-a-141",       "Soldado"),
    ("BrinoxAer",        "Soldado"),
    ("KP",               "Soldado"),
    ("Padrimp:p",        "Soldado"),
    ("Padrim:p",         "Soldado"),
    ("WeehHP",           "Soldado"),
    ("Cebollitaah",      "Soldado"),
    ("DRKZNBB",          "Soldado"),
    ("domaleffga27",     "Soldado"),
    ("xnetyy",           "Soldado"),
    ("sapequinhauwu",    "Soldado"),
    ("JalabuG",          "Soldado"),
    ("Bolsonaro22.",     "Soldado"),
    ("ninguem",          "Soldado"),
    ("Ambition!",        "Soldado"),
    ("Hyvrnk",           "Soldado"),
    ("marlon6434",       "Soldado"),
    ("guinhoe",          "Soldado"),
    ("Orgib",            "Soldado"),
    ("ravennastar",      "Soldado"),
    ("Stanleyi",         "Soldado"),
    ("Wolfsburg",        "Soldado"),
    ("allanspvaleu",     "Soldado"),
    ("ricardomassa",     "Soldado"),
    ("Faxineiro.",       "Soldado"),
    ("CatatauDOE",       "Soldado"),
    ("Gabbrox",          "Soldado"),
    ("MariaBern",        "Soldado"),
    ("Avasts",           "Soldado"),
    ("future123",        "Soldado"),
    ("loco.pra@",        "Soldado"),
    ("LucasTTR",         "Soldado"),
    ("BabyDinossour",    "Soldado"),
    ("AdamDriver.",      "Soldado"),
    ("Hyuna-San",        "Soldado"),
    ("tiaraquelmiguxa",  "Soldado"),
    ("Egonx",            "Soldado"),
    (":O.ExIMPOSTOR:",   "Soldado"),
    ("KyloRen@",         "Soldado"),
    ("MaximusDeximus",   "Soldado"),
    ("emp1real",         "Soldado"),
    ("ser02j27-3",       "Soldado"),
    ("dep.didi1",        "Soldado"),
    ("Zelenkoq96554",    "Soldado"),
    ("lyx18",            "Soldado"),
    ("O34TOKYOO",        "Soldado"),
    ("..:Destemido:..",  "Soldado"),
    ("Excluido1",        "Soldado"),
    ("Ayala!",           "Soldado"),
    ("LucasFalke",       "Soldado"),
    ("mikaelarj-",       "Soldado"),
    ("nikkee",           "Soldado"),
    ("ebenicio",         "Soldado"),
    ("QueenElizabeta",   "Soldado"),
    ("ZenoQuill",        "Soldado"),
    ("BiaLovePopp@",     "Soldado"),
    ("mandscchab",       "Soldado"),
    ("JackOConnel",      "Soldado"),
    ("Yas2018",          "Soldado"),
    ("O.ExImpostor22",   "Soldado"),
    ("Hellennx",         "Soldado"),
    ("ser-0-7-0",        "Soldado"),
    ("heenry07",         "Soldado"),
    ("Edusanti99",       "Soldado"),
    ("AmandaNeves.",     "Soldado"),
    ("Christina.Ban",    "Soldado"),
    ("JuninhoPlay!",     "Soldado"),
    ("Manno",            "Soldado"),
    ("L.S1992",          "Soldado"),
    ("renegadorrrrrrr",  "Soldado"),
    ("TonyStarkNeto",    "Soldado"),
    ("Henrique21.",      "Soldado"),
    ("TestMail",         "Soldado"),
    ("EwanMitchell",     "Soldado"),
    ("Tanqq",            "Soldado"),
    ("Arata",            "Soldado"),
    ("PHA.ulinhaaaa",    "Soldado"),
    ("alexteixe",        "Soldado"),
    ("Ryomenn",          "Soldado"),
    ("ser91f-40-7",      "Soldado"),
    ("dreadsss",         "Soldado"),
    ("Vitor404",         "Soldado"),
    ("Vitor404!",        "Soldado"),
    ("ser0-s-31-6",      "Soldado"),
    ("Satron",           "Soldado"),
    ("Amanda",           "Soldado"),
    ("STEPLOKO",         "Soldado"),
    ("Luana...121",      "Soldado"),
    ("Skrillexa.",       "Soldado"),
    ("Stronda@Rara",     "Soldado"),
    ("vitiinho1612",     "Soldado"),
    ("LALA...1",         "Soldado"),
    ("Playssonheelki2",  "Soldado"),
    (".:PietroB:.",      "Soldado"),
    ("GUITORRESC",       "Soldado"),
    ("KittyXO",          "Soldado"),
    ("MichaelScott",     "Soldado"),
    ("emanuellela",      "Soldado"),
    ("Bullsay",          "Soldado"),
    ("noob2009",         "Soldado"),
    ("Th.Flow",          "Soldado"),
    ("-Divertida",       "Soldado"),
    ("JovemFla2",        "Soldado"),
    ("Dim3nor",          "Soldado"),
    ("ser1-n582",        "Soldado"),
    ("phmacielchi",      "Soldado"),
    ("Brunodel",         "Soldado"),
    ("SuperMachoMen",    "Soldado"),
    ("JamesBondi",       "Soldado"),
    ("KenpachiPro",      "Soldado"),
    ("agatalinda22",     "Soldado"),
    ("Leprassus",        "Soldado"),
    ("EnricoKlar",       "Soldado"),
    ("vertzes",          "Soldado"),
    ("Salvatore26",      "Soldado"),
    ("LegolasBlonde",    "Soldado"),
    ("thur12344",        "Soldado"),
    ("zefherion",        "Soldado"),
    ("Mizzkece",         "Soldado"),
    ("JelenaForever20",  "Soldado"),
    ("yasmimgonc70",     "Soldado"),
    ("marimoonie",       "Soldado"),
    ("milene9829",       "Soldado"),
    ("pudim692",         "Soldado"),
    ("gongombila",       "Soldado"),
    ("anaapratess",      "Soldado"),
    ("ser92-15",         "Soldado"),
    ("monizinha_",       "Soldado"),
    ("MENTALISTA.",      "Soldado"),
    ("Any-16.br",        "Soldado"),
    ("JoseOFidelis",     "Soldado"),
    ("@.!.Andre.!.@",    "Soldado"),
    ("BoycrisPixelada",  "Soldado"),
    ("Carolux",          "Soldado"),
    ("linda2007Lost",    "Soldado"),
    ("poc4nha",          "Soldado"),
]


def main():
    # De-duplica mantendo a primeira ocorrência (patente mais alta)
    seen = {}
    unique = []
    for nick, patente in ROSTER:
        if nick not in seen:
            seen[nick] = True
            unique.append((nick, patente))

    with psycopg.connect(DATABASE_URL) as conn:
        with conn.cursor() as cur:
            # Limpa militares e alto comando atuais para evitar conflitos
            cur.execute("DELETE FROM militares WHERE corpo IN ('militar', 'alto_comando')")
            
            for i, (nick, patente) in enumerate(unique):
                ordem = _ORDEM[patente]
                email = f"mil{i+1:04d}@dme.internal"
                
                # Se for Alto Comando Supremo, usa o corpo específico
                corpo = "alto_comando" if patente in {"Fundador", "Supremo", "Supremo Interino"} else "militar"
                
                cur.execute(
                    """
                    INSERT INTO militares
                        (nick, email, senha_hash, patente, patente_ordem,
                         corpo, status, role, tag, created_at)
                    VALUES (%s, %s, '', %s, %s, %s, 'ativo', 'user', 'DME', NOW())
                    ON CONFLICT (nick) DO UPDATE SET
                        patente       = EXCLUDED.patente,
                        patente_ordem = EXCLUDED.patente_ordem,
                        corpo         = EXCLUDED.corpo,
                        status        = 'ativo'
                    """,
                    (nick, email, patente, ordem, corpo),
                )
        conn.commit()
    print(f"✓ {len(unique)} membros militares importados com sucesso.")


if __name__ == "__main__":
    main()
